// Code generated by skgo. DO NOT EDIT.
import { command, query } from '$app/server';
import type { Change, Document, SaveRequest, SaveResult } from '../lib/skgo/editor/types';

export type { Change, Document, SaveRequest, SaveResult };

// Every body throws. These functions are implemented in Go, and skgo
// answers their endpoints itself, so anything that renders in the browser
// is proof the Go handler replied rather than this module.
const unimplemented = (): never => {
	throw new Error('skgo: implemented in Go');
};

export const getDoc = query((): Document => unimplemented());

export const saveDoc = command('unchecked', (_arg: SaveRequest): SaveResult => unimplemented());

export const watchDoc = query.live((): AsyncIterable<Change> => unimplemented());
