// Code generated by skgo. DO NOT EDIT.

package routes

import (
	editor "github.com/tylergannon/gimble/internal/editor"
)

// The functions this package declares, published under names the generated
// bindings package can spell. Each is the function itself and not a wrapper:
// skgo.Refresh finds a query by the code pointer of the function it names.
var (
	// Skgo_getDoc is getDoc, published as src/routes/editor.remote.ts#getDoc.
	Skgo_getDoc = getDoc
	// Skgo_saveDoc is saveDoc, published as src/routes/editor.remote.ts#saveDoc.
	Skgo_saveDoc = saveDoc
	// Skgo_watchDoc is watchDoc, published as src/routes/editor.remote.ts#watchDoc.
	Skgo_watchDoc = watchDoc
	// Skgo_pageLoad is pageLoad, published as the server load of src/routes/+page.server.ts.
	Skgo_pageLoad = pageLoad
)

type (
	// SkgoOut_watchDoc is the type watchDoc yields.
	SkgoOut_watchDoc = editor.Change
)
