// Code generated by skgo. DO NOT EDIT.

package routes

import "github.com/tylergannon/skgo"

// SkgoRemotes returns the remote functions declared in this package.
func SkgoRemotes() []*skgo.Remote {
	return []*skgo.Remote{
		skgo.NewQueryNoArg("src/routes/editor.remote.ts", "getDoc", getDoc),
		skgo.NewCommand("src/routes/editor.remote.ts", "saveDoc", saveDoc),
		skgo.NewLiveQueryNoArg("src/routes/editor.remote.ts", "watchDoc", watchDoc),
	}
}

// SkgoLoads returns the server loads declared in this package.
func SkgoLoads() []*skgo.ServerLoad {
	return []*skgo.ServerLoad{}
}

// SkgoEndpoints returns the server routes declared in this package.
func SkgoEndpoints() []*skgo.Endpoint {
	return []*skgo.Endpoint{}
}
