package main

import (
	"os"
	"path/filepath"
	"testing"
)

func TestDetachGeneratedDoc(t *testing.T) {
	path := filepath.Join(t.TempDir(), "generated.go")
	const source = "// Code generated by polytype. DO NOT EDIT.\npackage example\n"
	if err := os.WriteFile(path, []byte(source), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := detachGeneratedDoc(path); err != nil {
		t.Fatal(err)
	}
	contents, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	const want = "// Code generated by polytype. DO NOT EDIT.\n\npackage example\n"
	if string(contents) != want {
		t.Fatalf("generated file = %q", contents)
	}
	if err := detachGeneratedDoc(path); err != nil {
		t.Fatalf("second fixup: %v", err)
	}
}

func TestMaterializeReplacesSymlinkWithRegularFile(t *testing.T) {
	root := t.TempDir()
	target := filepath.Join(root, "target.go")
	linkDir := filepath.Join(root, "links")
	link := filepath.Join(linkDir, "target.go")
	if err := os.WriteFile(target, []byte("package example\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.Mkdir(linkDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(target, link); err != nil {
		t.Fatal(err)
	}

	if err := materialize(linkDir); err != nil {
		t.Fatal(err)
	}
	info, err := os.Lstat(link)
	if err != nil {
		t.Fatal(err)
	}
	if info.Mode()&os.ModeSymlink != 0 || !info.Mode().IsRegular() {
		t.Fatalf("materialized file mode = %v", info.Mode())
	}
	contents, err := os.ReadFile(link)
	if err != nil {
		t.Fatal(err)
	}
	if string(contents) != "package example\n" {
		t.Fatalf("materialized contents = %q", contents)
	}
}
