// Command generatefixups applies the small repository transformations that
// upstream generators cannot express themselves.
package main

import (
	"bytes"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
)

func main() {
	if len(os.Args) != 3 {
		usage()
	}
	var err error
	switch os.Args[1] {
	case "detach-doc":
		err = detachGeneratedDoc(os.Args[2])
	case "materialize":
		err = materialize(os.Args[2])
	default:
		usage()
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func usage() {
	fmt.Fprintln(os.Stderr, "usage: generatefixups (detach-doc FILE | materialize DIRECTORY)")
	os.Exit(2)
}

func detachGeneratedDoc(path string) error {
	contents, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	const attached = "// Code generated by polytype. DO NOT EDIT.\npackage "
	const detached = "// Code generated by polytype. DO NOT EDIT.\n\npackage "
	if bytes.Contains(contents, []byte(detached)) {
		return nil
	}
	updated := bytes.Replace(contents, []byte(attached), []byte(detached), 1)
	if bytes.Equal(updated, contents) {
		return fmt.Errorf("%s: Polytype generated marker is missing", path)
	}
	info, err := os.Stat(path)
	if err != nil {
		return err
	}
	return os.WriteFile(path, updated, info.Mode().Perm())
}

func materialize(root string) error {
	return filepath.WalkDir(root, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.Type()&os.ModeSymlink == 0 {
			return nil
		}
		info, err := os.Stat(path)
		if err != nil {
			return fmt.Errorf("stat %s: %w", path, err)
		}
		contents, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read %s: %w", path, err)
		}
		temporary, err := os.CreateTemp(filepath.Dir(path), ".materialize-*")
		if err != nil {
			return fmt.Errorf("stage %s: %w", path, err)
		}
		temporaryName := temporary.Name()
		defer os.Remove(temporaryName)
		if _, err := temporary.Write(contents); err != nil {
			_ = temporary.Close()
			return fmt.Errorf("write %s: %w", path, err)
		}
		if err := temporary.Chmod(info.Mode().Perm()); err != nil {
			_ = temporary.Close()
			return fmt.Errorf("chmod %s: %w", path, err)
		}
		if err := temporary.Close(); err != nil {
			return fmt.Errorf("close %s: %w", path, err)
		}
		if err := os.Remove(path); err != nil {
			return fmt.Errorf("remove link %s: %w", path, err)
		}
		if err := os.Rename(temporaryName, path); err != nil {
			return fmt.Errorf("replace link %s: %w", path, err)
		}
		return nil
	})
}
