// Code generated by polytype. DO NOT EDIT.

/**
 * Change announces a new version of the files on disk.
 */
export type Change = {
  /**
   * Version is Document.Version for the state now on disk.
   */
  "version": string;
};

/**
 * Document is what the page reads: the pipeline file, its layout sidecar, a version that changes whenever either file does, and what lint makes of it.
 */
export type Document = {
  /**
   * Path is the absolute path of the pipeline file.
   */
  "path": string;
  /**
   * YAML is the file's text, exactly as it is on disk.
   */
  "yaml": string;
  /**
   * Layout is every node placement the sidecar holds.
   */
  "layout": Array<Placement>;
  /**
   * HasLayout reports whether a layout sidecar exists beside the pipeline.
   */
  "has_layout": boolean;
  /**
   * Version identifies this state of the two files. A save must quote it.
   */
  "version": string;
  /**
   * Diagnostics are the lint findings, the same ones `tractor validate` prints.
   */
  "diagnostics": Array<Diagnostic>;
  /**
   * ParseError is set when the file does not parse; Diagnostics is empty then.
   */
  "parse_error": string;
  /**
   * Models says which model each node resolved to.
   */
  "models": Array<ModelResolution>;
};

/**
 * Placement is where one node sits on the canvas.
 */
export type Placement = {
  /**
   * ID is the node's id in the pipeline.
   */
  "id": string;
  /**
   * X is the left edge, in canvas units.
   */
  "x": number;
  /**
   * Y is the top edge, in canvas units.
   */
  "y": number;
  /**
   * W is the width; zero means the page decides.
   */
  "w": number;
  /**
   * H is the height; zero means the page decides.
   */
  "h": number;
};

/**
 * Diagnostic is one lint finding.
 */
export type Diagnostic = {
  /**
   * Rule names the lint rule that fired.
   */
  "rule": string;
  /**
   * Severity is error, warning, or info.
   */
  "severity": string;
  /**
   * Message says what is wrong.
   */
  "message": string;
  /**
   * NodeID is the node the finding belongs to, or empty.
   */
  "node_id": string;
  /**
   * Edge is the authored edge the finding belongs to, as from and to, or empty.
   */
  "edge": Array<string>;
  /**
   * Fix suggests what to change, or is empty.
   */
  "fix": string;
};

/**
 * ModelResolution says which model a node resolved to and why.
 */
export type ModelResolution = {
  "node_id": string;
  "role": string;
  "source": string;
  "authored_name": string;
  "authored_version": string;
  "native_model": string;
  "effective_effort": string;
  "provider": string;
  "harness": string;
};

/**
 * SaveRequest is what the page sends to write the file.
 */
export type SaveRequest = {
  /**
   * YAML is the whole file to write.
   */
  "yaml": string;
  /**
   * Layout is the placements to write to the sidecar when WriteLayout is set.
   */
  "layout": Array<Placement>;
  /**
   * WriteLayout says whether to write the sidecar at all. A page that has not moved a node leaves a pipeline without one alone.
   */
  "write_layout": boolean;
  /**
   * Version is the Document.Version the page last saw. A save against any other version is refused and the current document is returned instead.
   */
  "version": string;
};

/**
 * SaveResult is the answer to a save.
 */
export type SaveResult = {
  /**
   * Saved is false when the file changed on disk since the page last read it; nothing was written and Document is what is on disk now.
   */
  "saved": boolean;
  /**
   * Document is the state after the save, or the state that refused it.
   */
  "document": Document;
};
