//go:build jsonschema

// Code generated by skgo. DO NOT EDIT.

package editor

import (
	"encoding/json"

	"github.com/tylergannon/polytype"
)

// Stubs so the package compiles before polytype has run.
func (Change) Schema() json.RawMessage      { panic("not implemented") }
func (Document) Schema() json.RawMessage    { panic("not implemented") }
func (SaveRequest) Schema() json.RawMessage { panic("not implemented") }
func (SaveResult) Schema() json.RawMessage  { panic("not implemented") }

var (
	_ = polytype.Declare(Change.Schema)
	_ = polytype.Declare(Document.Schema)
	_ = polytype.Declare(SaveRequest.Schema)
	_ = polytype.Declare(SaveResult.Schema)
)
