// Code generated by skgo. DO NOT EDIT.
import { command, query } from '$app/server';
import type { Status } from './types';

export type { Status };

// Every body throws. These functions are implemented in Go, and skgo
// answers their endpoints itself, so anything that renders in the browser
// is proof the Go handler replied rather than this module.
const unimplemented = (): never => {
	throw new Error('skgo: implemented in Go');
};

export const greet = command('unchecked', (_arg: string): Status => unimplemented());

export const status = query((): Status => unimplemented());
