// Code generated by skgo. DO NOT EDIT.

package routes

// The functions this package declares, published under names the generated
// bindings package can spell. Each is the function itself and not a wrapper:
// skgo.Refresh finds a query by the code pointer of the function it names.
var (
	// Skgo_guide is guide, published as src/routes/guide.remote.ts#guide.
	Skgo_guide = guide
)
