// Code generated by polytype. DO NOT EDIT.

/**
 * Status is what the home page shows. Its fields cross to TypeScript, so it is the type the generated `types.ts` beside this file declares.
 */
export type Status = {
  /**
   * Name is the application's name.
   */
  "name": string;
  /**
   * GoVersion is the Go runtime that answered.
   */
  "goVersion": string;
  /**
   * Greetings counts the greetings this process has served.
   */
  "greetings": number;
  /**
   * LastGreeting is who was greeted last.
   */
  "lastGreeting": string;
};
