// Code generated by polytype. DO NOT EDIT.

package skgo

import (
	"encoding/json"
	"fmt"
	pkg_onzggl3sn52xizlt "github.com/tylergannon/gimble/internal/skgo/links/onzggl3sn52xizlt"
	devalue "github.com/tylergannon/polytype/devalue"
	"math"
	"slices"
	"strconv"
	"time"
)

// dvAt renders a JSON-pointer-style path for a diagnostic. The root value has
// the empty path, which is spelled "/" so a message never starts with ": ".
func dvAt(at string) string {
	if at == "" {
		return "/"
	}
	return at
}

func dvErr(at string, format string, args ...any) error {
	return fmt.Errorf("%s: %s", dvAt(at), fmt.Sprintf(format, args...))
}

// dvKind names the devalue value model kind of v for wrong-kind diagnostics.
// Every tagged form is named so a rejected Date or Map says which one it was.
func dvKind(v any) string {
	switch v.(type) {
	case nil:
		return "null"
	case devalue.UndefinedValue:
		return "undefined"
	case devalue.HoleValue:
		return "a sparse-array hole"
	case bool:
		return "a boolean"
	case float64:
		return "a number"
	case string:
		return "a string"
	case []any:
		return "an array"
	case *devalue.Object:
		return "an object"
	case devalue.Date:
		return "a Date"
	case *devalue.Map:
		return "a Map"
	case *devalue.Set:
		return "a Set"
	case devalue.BigInt:
		return "a BigInt"
	case devalue.RegExp:
		return "a RegExp"
	case devalue.ArrayBuffer:
		return "an ArrayBuffer"
	case *devalue.Boxed:
		return "a boxed primitive"
	default:
		return fmt.Sprintf("a value of type %T", v)
	}
}

func dvBool(raw any, at string) (bool, error) {
	v, ok := raw.(bool)
	if !ok {
		return false, dvErr(at, "expected a boolean, got %s", dvKind(raw))
	}
	return v, nil
}

func dvString(raw any, at string) (string, error) {
	v, ok := raw.(string)
	if !ok {
		return "", dvErr(at, "expected a string, got %s", dvKind(raw))
	}
	return v, nil
}

func dvNumber(raw any, at string) (float64, error) {
	v, ok := raw.(float64)
	if !ok {
		return 0, dvErr(at, "expected a number, got %s", dvKind(raw))
	}
	return v, nil
}

// dvFloat32 narrows a wire number, refusing values outside float32's range so
// a decode never silently yields an infinity.
func dvFloat32(raw any, at string) (float32, error) {
	v, err := dvNumber(raw, at)
	if err != nil {
		return 0, err
	}
	if !math.IsInf(v, 0) && !math.IsNaN(v) && math.Abs(v) > math.MaxFloat32 {
		return 0, dvErr(at, "number %v is out of range for float32", v)
	}
	return float32(v), nil
}

// dvInteger admits only integral numbers inside [min, max]. The bounds are
// float64 because every wire number is one; kinds wider than 2^53 are checked
// against the rounded bound, which is the same precision the encoder has.
func dvInteger(raw any, at string, min, max float64) (float64, error) {
	v, err := dvNumber(raw, at)
	if err != nil {
		return 0, err
	}
	if math.IsInf(v, 0) || math.IsNaN(v) || v != math.Trunc(v) {
		return 0, dvErr(at, "expected an integer, got %v", v)
	}
	if v < min || v > max {
		return 0, dvErr(at, "number %v is out of range", v)
	}
	return v, nil
}

func dvArray(raw any, at string) ([]any, error) {
	v, ok := raw.([]any)
	if !ok {
		return nil, dvErr(at, "expected an array, got %s", dvKind(raw))
	}
	for i, item := range v {
		if _, hole := item.(devalue.HoleValue); hole {
			return nil, dvErr(at+"/"+strconv.Itoa(i), "array element is a hole")
		}
	}
	return v, nil
}

func dvObject(raw any, at string) (*devalue.Object, error) {
	v, ok := raw.(*devalue.Object)
	if !ok {
		return nil, dvErr(at, "expected an object, got %s", dvKind(raw))
	}
	return v, nil
}

func dvKnown(o *devalue.Object, at string, known ...string) error {
	for _, key := range o.Keys() {
		if !slices.Contains(known, key) {
			return dvErr(at, "unknown property %q", key)
		}
	}
	return nil
}

// dvRequired reads a property that must be present and must not be undefined.
// at is the property's own path, so the diagnostic points at the value.
func dvRequired(o *devalue.Object, key string, at string) (any, error) {
	v, ok := o.Get(key)
	if !ok {
		return nil, dvErr(at, "missing required property %q", key)
	}
	if _, undefined := v.(devalue.UndefinedValue); undefined {
		return nil, dvErr(at, "value is undefined")
	}
	return v, nil
}

// dvPresent reads an optional property. It reports absence, and rejects an
// explicit undefined, which is not the same thing on this wire.
func dvPresent(o *devalue.Object, key string, at string) (any, bool, error) {
	v, ok := o.Get(key)
	if !ok {
		return nil, false, nil
	}
	if _, undefined := v.(devalue.UndefinedValue); undefined {
		return nil, false, dvErr(at, "value is undefined")
	}
	return v, true, nil
}

// dvWithout copies o omitting key, so a union payload decoder does not see the
// discriminator it never declared as a field.
func dvWithout(o *devalue.Object, key string) *devalue.Object {
	out := devalue.NewObject()
	for _, k := range o.Keys() {
		if k == key {
			continue
		}
		v, _ := o.Get(k)
		out.Set(k, v)
	}
	return out
}

// dvTagged rebuilds a union payload with the discriminator first, leaving any
// discriminator the payload itself carried out of the result.
func dvTagged(payload any, discriminator string, tag string, at string) (any, error) {
	o, err := dvObject(payload, at)
	if err != nil {
		return nil, err
	}
	out := devalue.NewObject()
	out.Set(discriminator, tag)
	for _, k := range o.Keys() {
		if k == discriminator {
			continue
		}
		v, _ := o.Get(k)
		out.Set(k, v)
	}
	return out, nil
}

// dvEncodeTime and dvDecodeTime use time.Time's own JSON methods, so the wire
// string is exactly the one encoding/json would produce and accept.
func dvEncodeTime(v time.Time, at string) (any, error) {
	encoded, err := v.MarshalJSON()
	if err != nil {
		return nil, dvErr(at, "%v", err)
	}
	var s string
	if err := json.Unmarshal(encoded, &s); err != nil {
		return nil, dvErr(at, "%v", err)
	}
	return s, nil
}

func dvDecodeTime(raw any, at string) (time.Time, error) {
	s, err := dvString(raw, at)
	if err != nil {
		return time.Time{}, err
	}
	quoted, err := json.Marshal(s)
	if err != nil {
		return time.Time{}, dvErr(at, "%v", err)
	}
	var v time.Time
	if err := v.UnmarshalJSON(quoted); err != nil {
		return time.Time{}, dvErr(at, "%v", err)
	}
	return v, nil
}

func encStatus(v pkg_onzggl3sn52xizlt.Status, at string) (any, error) {
	enc1 := devalue.NewObject()
	var enc2 any = string(v.Name)
	enc1.Set("name", enc2)
	var enc3 any = string(v.GoVersion)
	enc1.Set("goVersion", enc3)
	var enc4 any = float64(v.Greetings)
	enc1.Set("greetings", enc4)
	var enc5 any = string(v.LastGreeting)
	enc1.Set("lastGreeting", enc5)
	return enc1, nil
}

func decStatus(raw any, at string) (pkg_onzggl3sn52xizlt.Status, error) {
	var dvZero pkg_onzggl3sn52xizlt.Status
	var dec1 pkg_onzggl3sn52xizlt.Status
	obj2, err := dvObject(raw, at)
	if err != nil {
		return dvZero, err
	}
	if err := dvKnown(obj2, at, "name", "goVersion", "greetings", "lastGreeting"); err != nil {
		return dvZero, err
	}
	raw3, err := dvRequired(obj2, "name", at+"/name")
	if err != nil {
		return dvZero, err
	}
	dec4, err := dvString(raw3, at+"/name")
	if err != nil {
		return dvZero, err
	}
	dec1.Name = dec4
	raw5, err := dvRequired(obj2, "goVersion", at+"/goVersion")
	if err != nil {
		return dvZero, err
	}
	dec6, err := dvString(raw5, at+"/goVersion")
	if err != nil {
		return dvZero, err
	}
	dec1.GoVersion = dec6
	raw7, err := dvRequired(obj2, "greetings", at+"/greetings")
	if err != nil {
		return dvZero, err
	}
	num9, err := dvInteger(raw7, at+"/greetings", math.MinInt, math.MaxInt)
	if err != nil {
		return dvZero, err
	}
	dec8 := int(num9)
	dec1.Greetings = dec8
	raw10, err := dvRequired(obj2, "lastGreeting", at+"/lastGreeting")
	if err != nil {
		return dvZero, err
	}
	dec11, err := dvString(raw10, at+"/lastGreeting")
	if err != nil {
		return dvZero, err
	}
	dec1.LastGreeting = dec11
	return dec1, nil
}

// EncodeStatus converts v into the devalue value model.
func EncodeStatus(v pkg_onzggl3sn52xizlt.Status) (any, error) { return encStatus(v, "") }

// DecodeStatus converts a devalue value model tree into a pkg_onzggl3sn52xizlt.Status, rejecting any
// shape the type grammar does not admit.
func DecodeStatus(raw any) (pkg_onzggl3sn52xizlt.Status, error) { return decStatus(raw, "") }

// StringifyStatus encodes v and serializes it with devalue.
func StringifyStatus(v pkg_onzggl3sn52xizlt.Status) (string, error) {
	encoded, err := encStatus(v, "")
	if err != nil {
		return "", err
	}
	return devalue.Stringify(encoded)
}

// ParseStatus parses a devalue document and decodes it into a pkg_onzggl3sn52xizlt.Status.
func ParseStatus(s string) (pkg_onzggl3sn52xizlt.Status, error) {
	var zero pkg_onzggl3sn52xizlt.Status
	parsed, err := devalue.Parse(s, nil)
	if err != nil {
		return zero, err
	}
	return decStatus(parsed, "")
}

func encRoot0(v string, at string) (any, error) {
	var enc1 any = string(v)
	return enc1, nil
}

func decRoot0(raw any, at string) (string, error) {
	var dvZero string
	dec1, err := dvString(raw, at)
	if err != nil {
		return dvZero, err
	}
	return dec1, nil
}

// EncodeRoot0 converts v into the devalue value model.
func EncodeRoot0(v string) (any, error) { return encRoot0(v, "") }

// DecodeRoot0 converts a devalue value model tree into a string, rejecting any
// shape the type grammar does not admit.
func DecodeRoot0(raw any) (string, error) { return decRoot0(raw, "") }

// StringifyRoot0 encodes v and serializes it with devalue.
func StringifyRoot0(v string) (string, error) {
	encoded, err := encRoot0(v, "")
	if err != nil {
		return "", err
	}
	return devalue.Stringify(encoded)
}

// ParseRoot0 parses a devalue document and decodes it into a string.
func ParseRoot0(s string) (string, error) {
	var zero string
	parsed, err := devalue.Parse(s, nil)
	if err != nil {
		return zero, err
	}
	return decRoot0(parsed, "")
}

func encRoot1(v pkg_onzggl3sn52xizlt.Status, at string) (any, error) {
	enc1, err := encStatus(v, at)
	if err != nil {
		return nil, err
	}
	return enc1, nil
}

func decRoot1(raw any, at string) (pkg_onzggl3sn52xizlt.Status, error) {
	var dvZero pkg_onzggl3sn52xizlt.Status
	dec1, err := decStatus(raw, at)
	if err != nil {
		return dvZero, err
	}
	return dec1, nil
}

// EncodeRoot1 converts v into the devalue value model.
func EncodeRoot1(v pkg_onzggl3sn52xizlt.Status) (any, error) { return encRoot1(v, "") }

// DecodeRoot1 converts a devalue value model tree into a pkg_onzggl3sn52xizlt.Status, rejecting any
// shape the type grammar does not admit.
func DecodeRoot1(raw any) (pkg_onzggl3sn52xizlt.Status, error) { return decRoot1(raw, "") }

// StringifyRoot1 encodes v and serializes it with devalue.
func StringifyRoot1(v pkg_onzggl3sn52xizlt.Status) (string, error) {
	encoded, err := encRoot1(v, "")
	if err != nil {
		return "", err
	}
	return devalue.Stringify(encoded)
}

// ParseRoot1 parses a devalue document and decodes it into a pkg_onzggl3sn52xizlt.Status.
func ParseRoot1(s string) (pkg_onzggl3sn52xizlt.Status, error) {
	var zero pkg_onzggl3sn52xizlt.Status
	parsed, err := devalue.Parse(s, nil)
	if err != nil {
		return zero, err
	}
	return decRoot1(parsed, "")
}
