// Code generated by skgo. DO NOT EDIT.

package skgo

import (
	"context"

	"github.com/tylergannon/skgo"

	skgo0 "github.com/tylergannon/gimble/internal/skgo/links/onzggl3sn52xizlt"
)

// remote_guide answers src/routes/guide.remote.ts#guide, a query.
//
// It takes no argument, so any argument at all is refused — kit's own
// validator for a function declared without one answers 400 too.
// The result is encoded by EncodeRoot0, generated for its result type.
func remote_guide(ctx context.Context, call skgo.Call) (any, error) {
	if err := skgo.RefuseArgument(call); err != nil {
		return nil, err
	}
	out, err := skgo0.Skgo_guide(ctx)
	if err != nil {
		return nil, err
	}
	return EncodeRoot0(out)
}

// Remotes returns every remote function declared in the app, ready to hand
// to skgo.NewRemotes.
func Remotes() []*skgo.Remote {
	return []*skgo.Remote{
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:   skgo.KindQuery,
			Module: "src/routes/guide.remote.ts",
			Name:   "guide",
			Fn:     skgo0.Skgo_guide,
			Call:   remote_guide,
		}),
	}
}

// Loads returns every server load declared in the app, ready to hand to
// skgo.NewLoads.
func Loads() []*skgo.ServerLoad {
	return []*skgo.ServerLoad{}
}

// Endpoints returns every server route declared in the app, ready to hand
// to skgo.NewEndpoints.
func Endpoints() []*skgo.Endpoint {
	return []*skgo.Endpoint{}
}
